% Main script for conversion of markerless mocap data to QTM export
% formats.
% 
% Assumes PAF project structure
% 
% Conversion of Theia skeleton data from Theia C3D output to QTM TSV via
% Visual3D MAT export
% 
% Set project root as working directory
% Run script (recommended to run one cell at the time and clear data in between)

%% Script parameters
Opts = struct(...
    'qtm_project_root_check',true,... % Check if the current folder is a QTM project root folder (contains "Data" subfolder)
    'theia_output_folder','TheiaFormatData',...
    'qtm_data_folder_rel_theia_output_folder','..',... % QTM data folder location relative to theia output folder (in PAF it is the folder above the Theia output folder)
    'qtm_format_output_folder', {{'theia_data_path','qtm_format'}},... % Cell containing data_path (qtm_/theia_data_path, as defined in trial admin) and subfolder for storing converted data (QTM export format)
    'qtm_format_output_suffix', '',... % Suffix appended to trial file name for the converted output
    'admin_file', 'admin.xlsx',...
    'trial_sheet', 'trials',...
    'trialVarDef', {{... % Variables for trial admin - DO NOT EDIT % 'subject_folder','string';... 'session_folder','string';...
        'theia_data_path','string';...
        'qtm_data_path','string';...
        'qtm_format_output_path','string';...
        'trial','string';...
        'trial_output_name','string';...
        'n_skel','double';...
        'processing_date','string'}},...
    'max_trials', 1000,...
    'write_skeleton_info',true,...
    'skeleton_info_sheet', 'skeleton_info',...
    'skelVarDef',{{... % Additional variables for skeleton admin (added to trial admin variables) - DO NOT EDIT
        'theia_version','string';...
        'skel_id','string';...
        'model','string';...
        'n_frames','double';...
        'frame_rate','double';...
        'n_segments','double';...
        'fill_level_av','double';...
        'fill_level_sd','double';...
        'fill_level_min','double';...
        'fill_level_max','double'}},...
    'theia_pose_base', 'pose_filt',...
    'rot_suffix', '_4X4',...
    'ignore_segments', {{'worldbody'}},... % List of rotation segments to ignore (without rot_suffix)
    'default_model', 'standard',...
    'animation_model', 'animation',...
    'animation_model_segments', {{'abdomen','thorax','neck'}},...
    'verbose', true);

%% Create trial admin

Create_project_admin(Opts);

% Creates a project admin file in the project root: admin.xlsx
% 
% Review the admin, optionally remove rows to discard further
% processing. The following scripts will process the trials specified in
% the sheet "trials".

%% Convert Theia C3D files to QTM skeleton representation (QTM .mat export format)

% clearvars
C3D_to_QTM_mat(Opts);

%% Convert QTM mat to QTM TSV skeletons (QTM .tsv skeleton format)

% clearvars
QTM_mat_to_tsv(Opts);
