% Main script for conversion of markerless mocap data to QTM export
% formats.
% 
% Assumes PAF project structure
% 
% Conversion of Theia skeleton data from Theia C3D output to QTM TSV via
% Visual3D MAT export
% 
% Set project root as working directory
% Run script (recommended to run one cell at the time and clear data in between)

%% Script parameters
Opts = struct(...
    'admin_file', 'admin.xlsx',...
    'data_folder', 'Data',...
    'theia_output_folder','TheiaFormatData',...
    'trial_sheet', 'trials',...
    'trialVarDef', {{... 'subject_folder','string';... 'session_folder','string';...
        'data_folder','string';...
        'trial','string';...
        'n_skel','double';...
        'processing_date','string'}},...
    'max_rows', 1000,...
    'skel_sheet', 'skeletons',...
    'theia_pose_base', 'pose_filt',...
    'rot_suffix', '_4X4',...
    'ignore_segments', {{'worldbody'}},... % List of rotation segments to ignore (without suffix)
    'default_model', 'standard',...
    'animation_model', 'animation',...
    'animation_model_segments', {{'abdomen','thorax','neck'}},...
    'qtm_format_folder', 'qtm_format',...
    'verbose', true);

%% Create trial admin

Create_project_admin(Opts);

% Creates a project admin file in the project root: admin.xlsx
% 
% Review the admin, optionally remove rows to discard further
% processing. The following scripts will process the trials specified in
% the sheet "trials".

%% Convert Theia C3D files to QTM skeleton representation (QTM .mat export format)

% clearvars
C3D_to_QTM_mat;

%% Convert QTM mat to QTM TSV skeletons (QTM .tsv skeleton format)

% clearvars
QTM_mat_to_tsv;
